### ISSUE TITLE
Error LNK2001 eye_gaze v1.0 

### ISSUE THREAD

**Issue by gitvbs00** [iitmcvg/eye-gaze#1]
@Aravind-Shankar  Hi,  i try to run this program but i keep getting those errors  (you can see them in the  attachment Debug_Errors). I'm using Visual Studio 2012, opencv 2.4.9, this is how i include the dlib file 
C:...\Downloads\eye-gaze-1.0\eye-gaze-1.0\src 

[Debug_Errors.txt](https://github.com/iitmcvg/eye-gaze/files/191229/Debug_Errors.txt)
Thank you for your help.

**Comment by Aravind-Suresh** [comment]
These errors are OpenCV linker errors. Check if you compile with appropriate libraries. It throws linker errors for cvtColor, KalmanFilter etc. Also, they are not related to Dlib in any way.

PS: I am @Aravind-Suresh.

**Comment by rsnk96** [comment]
Hi

Check your Property Page -->Linker-->Input-->Include Directories. Make sure there's a 'd' appended to the end of each library name (i.e., "opencv_core249d.dll", not "opencv_core249.dll") Visual Studio expects a debug library for a debug compilation.

**Comment by gitvbs00** [comment]
@Aravind-Suresh  Sorry it was a typo. 
@Aravind-Suresh, @rsnk96 Thank you, it's running now, there were missing some static libraries. 
However, it's showing the message "zero faces" on the debug windows while on the other one, only a snapshot image (no video feed ). Also it's taking a lot of time before processing.

**Comment by Aravind-Suresh** [comment]
It may take a lot of time if Dlib libraries are not linked properly. They need to be built with appropriate flags. Check cmake file. I faced the same problem, but once compiling it with correct optimisation flags, it was faster.

**Comment by gitvbs00** [comment]
It's working now, I restarted Visual Studio, and linked again all the static libraries. 
Do you know a way I could use the eye-gaze to move the cursor by where the user is looking at.

**Comment by Aravind-Suresh** [comment]
Eye gaze gives you raw details about gaze vectors and pose. Use libraries like x11 for Linux ( Win32 provides tools for mouse controls in Windows ), and then control mouse using these values. Online forums will help you.

Hence, closing this issue. Thanks for your time :)

**Comment by iev6** [comment]
Umm, isnt that the whole point of this project? Calibration needs to be
done, for that. you need to define starting points and termination points,
with some kind of an interpolation formula while tracking the gaze.

*Giridhur S *
Undergraduate Junior
Electrical Engineering
Indian Institute of Technology,Madras

**Comment by gitvbs00** [comment]
Thank you guys. I will work on it.
