### ISSUE TITLE
Get X and Y Coordinates of Eye

### ISSUE THREAD

**Issue by ArfaouiHamouda** [iitmcvg/eye-gaze#10]
Hi,
Thanks for your great work , i want to get X and Y coordinates in order to use them in another Project , still can't figure out the Code yet and can't find the Correct Variables if you are using Ones .
Thanks .

**Comment by iev6** [comment]
check the files in "src" folder,  they'll have examples for calling the dlib routines. Please note that this code is very old, the library could have changed now.
