### ISSUE TITLE
Could the project run on windows system?

### ISSUE THREAD

**Issue by tjusxh** [iitmcvg/eye-gaze#11]
Could the project run on windows system?

**Comment by iev6** [comment]
yes, please install the necessary dependencies, opencv and dlib

**Comment by matteomel** [comment]
hi, I'm trying to run the program in windows, without succes. This what i do, am i missing something?
-download folder
-open visual studio cmd prompt
-nmake
i get error:  fatal error U1001: syntax error : character '^' not valid in the macro.
Can someone help me? I am not skilled in programming..
Many thanks
