### ISSUE TITLE
This  program cannot run

### ISSUE THREAD

**Issue by Hardold** [iitmcvg/eye-gaze#2]
Can the program run ?  When I compile, there are a lot of code errors. Can you give me a program that can be used normally? Thinks a lot !

**Comment by iev6** [comment]
Hello, @Hardold  please change to the demo branch, download the zip and  try again. It worked for me.

**Comment by Hardold** [comment]
Thinks a lot !  It can worked for me. But I noticed the code of faceModel.h and faceModel.cpp has some errors,  is it not completed yet ?

**Comment by Aravind-Suresh** [comment]
Yeah. faceModel.\* was branched out and we worked on another [repository](https://github.com/mrupeshkumar/FaZe).

**Comment by Hardold** [comment]
Thank you for your reply.

**Comment by Hardold** [comment]
Hi,
   I find that the value of  roll (5300) may seem odd. Any suggestion?
